### PR TITLE
Use a netstandard dll for build tasks instead of inline fragments. Th…

### PR DESCRIPTION
**Pull request by StephenMolloy**
…is will allow building SDK-style full framework projects with 'dotnet build.'

This should address #51

### CODE REVIEW

**Comment by Legends** [comment]
@StephenMolloy :

Looks like `CodeTaskFactory` is not supported?

> C:\Users\...\gitrepo.csproj(107,5): error MSB4801: The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild.
>      1>C:\Users\...\gitrepo.csproj(107,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files\dotnet\sdk\3.1.400-preview-015178\Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property.

**Comment by StephenMolloy** [comment]
That's correct? This PR was created to remove the dependency on CodeTaskFactory. The 3.5.0-preview version of this package on nuget should work with .Net Core MSBuild. An RTM version should be released within a few days.

**Comment by gprossliner** [comment]
@StephenMolloy can you please elaborate how it should be possible to convert asp.net 4.8 projects to SDK csproj, in order to build it with `dotnet build`?

The published nuget package (https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform) still doesn't have .netstandard or net6/7 as a target.

Thanks!

**Comment by StephenMolloy** [comment]
I don't know that ASP.Net projects are supported as SDK-style projects. For a long time they weren't. I don't know if that still holds true, or if that stance has changed to simply "discouraged." There are numerous guides on the internet for manually converting projects to SDK-style though, and you could follow those with an ASP.Net project if you wanted to, but I wouldn't worry about going that route unless you absolutely have to. There might be some things that don't work right with nuget dependencies in an ASP.Net environment.

But CodeDomProviders are technically available to be used in any .Net _Framework_ project. ASP.Net is just by far the primary use case. Non-ASP.Net projects can benefit from this project as well, so this PR was intended to support those cases that are using SDK-style and netstandard running on full .Net Framework.

As far as .Net 6.0/7.0... these packages don't support .Net Core. Only the full .Net Framework, so 4.8 is it.

**Pull request merged**
